package com.suviridedriver.model.get_profile

data class Data(
    val Status: String,
    val __v: Int,
    val _id: String,
    val angle: Int,
    val autoVerified: Boolean,
    val bankDetails: BankDetails,
    val city: String,
    val complaints: List<Any>,
    val createdAt: String,
    val currentLocation: CurrentLocation,
    val currentRide: List<Any>,
    val deviceToken: String,
    val discountOffer: String,
    val drivingLicence: DrivingLicence,
    val isAvailable: Boolean,
    val isDeleted: Boolean,
    val language: String,
    val lastLocationUpdate: String,
    val mobileNumber: Long,
    val `package`: String,
    val passengerCapacity: Int,
    val paymentVerification: String,
    val remainingRides: Int,
    val state: String,
    val takeSelfie: TakeSelfie,
    val token: String,
    val totalRides: Int,
    val updatedAt: String,
    val vehicleType: String,
    val vehiclesDetails: VehiclesDetails,
    val verificationStatus: String
)